
# FILE WITH ALL THE DATA NEEDED

BULLET_p_WIDTH = 12
BULLET_p_HEIGHT = 10
BULLET_p_SPEED = 8
BULLET_e_WIDTH = 4
BULLET_e_HEIGHT = 4
BULLET_e_SPEED = 8
PROG_WIDTH = 200
PROG_HEIGHT = 250


Plane_SPEED = 3
Plane_WIDTH = 24
Plane_HEIGHT = 15
Javi_WIDTH = 16
Javi_HEIGHT = 14
Javi_SPEED = 1
Liang_WIDTH = 14
Liang_HEIGHT = 14
Liang_SPEED = 1.5
Diego_WIDTH = 32
Diego_HEIGHT = 18
Diego_SPEED = 2
Barbara_WIDTH = 64
Barbara_HEIGHT = 52
Barbara_SPEED = 1
BULLET_d_WIDTH = 12
BULLET_d_HEIGHT = 10
BULLET_d_SPEED = 7
